spring:
  profiles:
    active: dev  #启用开发配置
#java -jar project-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev;
---
server:
  port: 7777
spring:
  profiles: dev
  datasource:
    username: root
    password: 550098879
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC





---
server:
  port: 80
spring:
  profiles: prod  #生产环境

---
