spring:
  profiles:
    active: dev  #启用开发配置
#java -jar project-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev;
---
server:
  port: 8080
spring:
  profiles: dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 550098879
#    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver





---
server:
  port: 80
spring:
  profiles: prod  #生产环境

---
